### ISSUE TITLE
Support of Budgie?

### ISSUE THREAD

**Issue by teras** [mind-overflow/gnome-fs-duplicate-cursor-fix#1]
Hello!
Your script on gnome works great! The annoying double cursor is gone!
Unfortunately, since I migrated to Budgie (since gnome had serious issues with full screen applications) it doesn't work any more. Probably because this script is heavily tied with gnome. 
Since Budgie is basically gnome-based, and the annoying double cursor is there, any idea what I should do to overcome this problem?

Thank you!

**Comment by mind-overflow** [comment]
Hey, thanks for showing interest in this!  
Sure, I can look into adding support for Budgie! The fix actually relies on two main things: having a `monitors.xml` file in the `~/.config/` directory (or at least somewhere), and being able to restart GNOME (Budgie, in this case) via a terminal command. If any of those two things are missing, then adding support might get a little more difficult, but otherwise, changing a few lines will be sufficient.  

I'll get a Budgie instance running in a little, but in the meanwhile - if you run the script manually, does it stop saying `File "monitors.xml" does not exist!`, or does it keep going but without actually doing anything?  

Also, I saw you forked the repo. Feel free to send a pull request if you manage to find a way! I'll have to wait a day or two before actually being able to work on this. I just pushed a commit that includes two files I accidentally forgot.  

Thanks!

**Comment by teras** [comment]
Thank you for the reply.
The file ~/.config/monitors.xml is there
I think the problem is with restarting budgie, since it tries to restart gnome instead.

Having said that, I also tried [the other solution](https://bugs.launchpad.net/ubuntu/+source/mutter/+bug/1873052/comments/8) mentioned in the bug report, and it works also with budgie. Having a second look of what the other solution is doing, it seems to be more like a universal solution

**Comment by mind-overflow** [comment]
> a script that toggles the scaling mode back and forth to fix the problem and then restore your desired scaling mode

Yeah well, this is pretty much what my one does too, haha. I really didn't notice that one, but I'm doing exactly the same thing - just in another way. If it works for you, I guess there is no need to even support this anymore - it requires a JVM and multiple files to work. That one script does it in just a few lines 😅.

**Comment by teras** [comment]
True. Thank you for the support anyway :)
